In [2]:

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel
from torch.optim import AdamW
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
import os
import random
from tqdm import tqdm
import warnings

warnings.filterwarnings("ignore")

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", DEVICE)

LOCAL_MODEL_DIR = "./hf_models"
MODEL_PATH = os.path.join(LOCAL_MODEL_DIR, "roberta-base")

LABEL2ID = {
    "Normal": 0,
    "Anxiety": 1,
    "Depression": 2,
    "Suicidal": 3
}
ID2LABEL = {v: k for k, v in LABEL2ID.items()}
CLASS_NAMES = ["Normal", "Anxiety", "Depression", "Suicidal"]

NOR_IDX, ANX_IDX, DEP_IDX, SUI_IDX = 0, 1, 2, 3

print("Severity-ordered label mapping:")
for k, v in LABEL2ID.items():
    print(f"  {v} -> {k}")


df = pd.read_csv("mental_heath_unbanlanced.csv")
df = df.dropna(subset=["text", "status"])
df["text"] = df["text"].astype(str)


df["label_encoded"] = df["status"].map(LABEL2ID)


if df["label_encoded"].isna().any():
    print("Warning: Unknown labels found!")
    print(df[df["label_encoded"].isna()]["status"].unique())

train_texts, temp_texts, train_labels, temp_labels = train_test_split(
    df["text"].tolist(),
    df["label_encoded"].tolist(),
    test_size=0.3,
    random_state=42,
    stratify=df["label_encoded"]
)

val_texts, test_texts, val_labels, test_labels = train_test_split(
    temp_texts, temp_labels,
    test_size=0.5,
    random_state=42,
    stratify=temp_labels
)

print("\nTest set support counts:")
unique, counts = np.unique(test_labels, return_counts=True)
for u, c in zip(unique, counts):
    print(f"  {ID2LABEL[u]}: {c}")

# ====================== Dataset ======================
class AblationDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=96):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encoding = self.tokenizer(
            self.texts[idx],
            truncation=True,
            padding="max_length",
            max_length=self.max_length,
            return_tensors="pt"
        )
        return {
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "labels": torch.tensor(self.labels[idx], dtype=torch.long)
        }


class BaselineModel(nn.Module):
    def __init__(self, model_path):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(model_path, local_files_only=True)
        hidden = self.encoder.config.hidden_size
        self.classifier = nn.Linear(hidden, 4)

    def forward(self, input_ids, attention_mask, labels=None):
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        cls = outputs.last_hidden_state[:, 0, :]
        logits = self.classifier(cls)
        loss = F.cross_entropy(logits, labels) if labels is not None else None
        return {"loss": loss, "logits": logits}


class ClassWeightModel(nn.Module):
    def __init__(self, model_path):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(model_path, local_files_only=True)
        hidden = self.encoder.config.hidden_size
        self.classifier = nn.Linear(hidden, 4)

    def forward(self, input_ids, attention_mask, labels=None, class_weights=None):
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        cls = outputs.last_hidden_state[:, 0, :]
        logits = self.classifier(cls)
        loss = None
        if labels is not None:
            loss = F.cross_entropy(logits, labels, weight=class_weights)
        return {"loss": loss, "logits": logits}


class MultiLabelSeverityModel(nn.Module):
    def __init__(self, model_path):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(model_path, local_files_only=True)
        hidden = self.encoder.config.hidden_size
        self.symptom_classifier = nn.Linear(hidden, 3)  # Anxiety, Depression, Suicidal
        self.suicide_risk = nn.Sequential(
            nn.Linear(hidden, 128),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(128, 1),
            nn.Sigmoid()
        )

    def forward(self, input_ids, attention_mask, multi_labels=None, severity_labels=None):
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        cls = outputs.last_hidden_state[:, 0, :]
        symptom_logits = self.symptom_classifier(cls)
        risk_score = self.suicide_risk(cls).squeeze(-1)

        if multi_labels is not None:
            loss_symptom = F.binary_cross_entropy_with_logits(symptom_logits, multi_labels.float())
            loss_risk = F.mse_loss(risk_score, severity_labels)
            loss = loss_symptom + 1.2 * loss_risk
            return {"loss": loss, "symptom_logits": symptom_logits, "risk_score": risk_score}
        return {"symptom_logits": symptom_logits, "risk_score": risk_score}

    def predict(self, input_ids, attention_mask):
        out = self.forward(input_ids, attention_mask)
        symptom_prob = torch.sigmoid(out["symptom_logits"])
        risk = out["risk_score"]
        pred = torch.full((input_ids.size(0),), NOR_IDX, dtype=torch.long, device=input_ids.device)
        has_symptom = (symptom_prob > 0.5).any(dim=1)
        pred[has_symptom & (risk < 0.3)] = ANX_IDX
        pred[has_symptom & (risk >= 0.3) & (risk < 0.7)] = DEP_IDX
        pred[risk >= 0.7] = SUI_IDX
        return pred


class HierarchicalModel(nn.Module):
    def __init__(self, model_path):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(model_path, local_files_only=True)
        hidden = self.encoder.config.hidden_size
        self.l1 = nn.Linear(hidden, 2)   # 0: Normal, 1: Issue
        self.l2 = nn.Linear(hidden, 2)   # 0: Anxiety, 1: Dep/Sui
        self.sev = nn.Sequential(nn.Linear(hidden, 1), nn.Sigmoid())

    def forward(self, input_ids, attention_mask, labels=None):
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        cls = outputs.last_hidden_state[:, 0, :]
        l1 = self.l1(cls)
        l2 = self.l2(cls)
        sev = self.sev(cls).squeeze(-1)

        if labels is not None:
            l1_labels = (labels != NOR_IDX).long()
            issue_mask = (labels != NOR_IDX)
            l2_labels = torch.zeros_like(labels)
            l2_labels[labels == ANX_IDX] = 0
            l2_labels[(labels == DEP_IDX) | (labels == SUI_IDX)] = 1
            sev_labels = torch.zeros_like(labels, dtype=torch.float)
            sev_labels[labels == DEP_IDX] = 0.5
            sev_labels[labels == SUI_IDX] = 1.0

            loss_l1 = F.cross_entropy(l1, l1_labels)
            loss_l2 = (F.cross_entropy(l2[issue_mask], l2_labels[issue_mask])
                       if issue_mask.any() else torch.tensor(0.0, device=DEVICE))
            loss_sev = (F.mse_loss(sev[issue_mask], sev_labels[issue_mask])
                        if issue_mask.any() else torch.tensor(0.0, device=DEVICE))
            loss = loss_l1 + 0.8 * loss_l2 + 0.5 * loss_sev
            return {"loss": loss, "l1": l1, "l2": l2, "sev": sev}
        return {"l1": l1, "l2": l2, "sev": sev}

    def predict(self, input_ids, attention_mask):
        out = self.forward(input_ids, attention_mask)
        is_issue = torch.argmax(out["l1"], dim=1)
        is_dep_spec = torch.argmax(out["l2"], dim=1)
        sev = out["sev"]
        pred = torch.full_like(is_issue, NOR_IDX)
        issue = (is_issue == 1)
        pred[issue & (is_dep_spec == 0)] = ANX_IDX
        pred[issue & (is_dep_spec == 1) & (sev < 0.7)] = DEP_IDX
        pred[issue & (is_dep_spec == 1) & (sev >= 0.7)] = SUI_IDX
        return pred


class OrdinalModel(nn.Module):
    def __init__(self, model_path):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(model_path, local_files_only=True)
        hidden = self.encoder.config.hidden_size
        self.thresholds = nn.Linear(hidden, 3)

    def forward(self, input_ids, attention_mask, labels=None):
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        cls = outputs.last_hidden_state[:, 0, :]
        cum_logits = self.thresholds(cls)
        if labels is not None:
            cum_labels = torch.zeros((labels.size(0), 3), device=labels.device)
            for i in range(3):
                cum_labels[:, i] = (labels > i).float()
            loss = F.binary_cross_entropy_with_logits(cum_logits, cum_labels)
            return {"loss": loss, "cum_logits": cum_logits}
        return {"cum_logits": cum_logits}

    def predict(self, input_ids, attention_mask):
        out = self.forward(input_ids, attention_mask)
        probs = torch.sigmoid(out["cum_logits"])
        return torch.sum(probs > 0.5, dim=1).long()


print("数据 + 5个模型定义已就绪")

# ====================== 训练与评估 ======================
def compute_class_weights(labels, num_classes=4):
    counts = np.bincount(labels, minlength=num_classes)
    total = len(labels)
    weights = total / (num_classes * counts + 1e-6)
    return torch.tensor(weights, dtype=torch.float32).to(DEVICE)


def train_and_evaluate(model_class, model_name, epochs=5, batch_size=16, lr=2e-5,
                       use_class_weight=False, use_multilabel=False):
    print("\n" + "="*60)
    print(f"开始训练模型: {model_name}")
    print("="*60)

    tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, local_files_only=True)
    train_dataset = AblationDataset(train_texts, train_labels, tokenizer)
    val_dataset   = AblationDataset(val_texts,   val_labels,   tokenizer)
    test_dataset  = AblationDataset(test_texts,  test_labels,  tokenizer)

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader   = DataLoader(val_dataset,   batch_size=batch_size, shuffle=False)
    test_loader  = DataLoader(test_dataset,  batch_size=batch_size, shuffle=False)

    model = model_class(MODEL_PATH).to(DEVICE)
    optimizer = AdamW(model.parameters(), lr=lr)

    class_weights = compute_class_weights(train_labels) if use_class_weight else None
    best_val_f1 = 0.0
    best_path = f"best_{model_name.replace(' ', '_').replace('+', 'plus')}.pt"

    for epoch in range(1, epochs+1):
        model.train()
        total_loss = 0.0
        for batch in tqdm(train_loader, desc=f"Epoch {epoch}"):
            input_ids = batch["input_ids"].to(DEVICE)
            attention_mask = batch["attention_mask"].to(DEVICE)
            labels = batch["labels"].to(DEVICE)

            optimizer.zero_grad()

            if use_class_weight:
                out = model(input_ids, attention_mask, labels=labels, class_weights=class_weights)
            elif use_multilabel:
                multi = torch.zeros(labels.size(0), 3, device=DEVICE)
                multi[labels == ANX_IDX, 0] = 1
                multi[labels == DEP_IDX, 1] = 1
                multi[labels == SUI_IDX, 2] = 1
                sev = torch.zeros(labels.size(0), device=DEVICE)
                sev[labels == DEP_IDX] = 0.5
                sev[labels == SUI_IDX] = 0.9
                out = model(input_ids, attention_mask, multi_labels=multi, severity_labels=sev)
            else:
                out = model(input_ids, attention_mask, labels=labels)

            loss = out["loss"]
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        avg_loss = total_loss / len(train_loader)

        # Validation
        model.eval()
        val_preds, val_gts = [], []
        with torch.no_grad():
            for batch in val_loader:
                input_ids = batch["input_ids"].to(DEVICE)
                attention_mask = batch["attention_mask"].to(DEVICE)
                labels = batch["labels"].to(DEVICE)
                if hasattr(model, "predict"):
                    preds = model.predict(input_ids, attention_mask)
                else:
                    out = model(input_ids, attention_mask)
                    preds = torch.argmax(out["logits"], dim=1)
                val_preds.extend(preds.cpu().numpy())
                val_gts.extend(labels.cpu().numpy())

        val_f1 = f1_score(val_gts, val_preds, average="weighted")
        print(f"Epoch {epoch} Avg Loss: {avg_loss:.4f} | Val Weighted F1: {val_f1:.4f}")

        if val_f1 > best_val_f1:
            best_val_f1 = val_f1
            torch.save(model.state_dict(), best_path)
            print(f"Best model saved: {best_path} (Val F1: {val_f1:.4f})")

    # Test
    model.load_state_dict(torch.load(best_path, map_location=DEVICE))
    model.eval()
    test_preds, test_gts = [], []
    with torch.no_grad():
        for batch in test_loader:
            input_ids = batch["input_ids"].to(DEVICE)
            attention_mask = batch["attention_mask"].to(DEVICE)
            labels = batch["labels"].to(DEVICE)
            if hasattr(model, "predict"):
                preds = model.predict(input_ids, attention_mask)
            else:
                out = model(input_ids, attention_mask)
                preds = torch.argmax(out["logits"], dim=1)
            test_preds.extend(preds.cpu().numpy())
            test_gts.extend(labels.cpu().numpy())

    print(f"\n=== Test Results: {model_name} ===")
    report = classification_report(test_gts, test_preds, target_names=CLASS_NAMES, digits=4)
    print(report)

    cm = confusion_matrix(test_gts, test_preds)
    print("Confusion Matrix:")
    print(cm)

    report_dict = classification_report(test_gts, test_preds, target_names=CLASS_NAMES, output_dict=True)
    dep_f1 = report_dict["Depression"]["f1-score"]
    sui_f1 = report_dict["Suicidal"]["f1-score"]
    dep_to_sui = int(cm[DEP_IDX, SUI_IDX])
    sui_to_dep = int(cm[SUI_IDX, DEP_IDX])

    with open(f"{model_name.replace(' ', '_').replace('+', 'plus')}_test_report.txt", "w") as f:
        f.write(report + "\nConfusion Matrix:\n" + str(cm))
        f.write(f"\nDep→Sui: {dep_to_sui}, Sui→Dep: {sui_to_dep}\n")

    return {
        "model": model_name,
        "accuracy": accuracy_score(test_gts, test_preds),
        "weighted_f1": f1_score(test_gts, test_preds, average="weighted"),
        "macro_f1": f1_score(test_gts, test_preds, average="macro"),
        "dep_f1": dep_f1,
        "sui_f1": sui_f1,
        "dep_to_sui": dep_to_sui,
        "sui_to_dep": sui_to_dep
    }



results = []
results.append(train_and_evaluate(BaselineModel, "Baseline"))
results.append(train_and_evaluate(ClassWeightModel, "+ Class Weight", use_class_weight=True))
results.append(train_and_evaluate(MultiLabelSeverityModel, "+ Multi-label + Severity", use_multilabel=True))
results.append(train_and_evaluate(HierarchicalModel, "+ Hierarchical"))
results.append(train_and_evaluate(OrdinalModel, "+ Ordinal Regression"))


print("\n" + "="*70)
print("Corrected Classification Model Comparison Table (Severity Order)")
print("="*70)
print(f"{'Model':<30} {'Acc':<8} {'W-F1':<8} {'M-F1':<8} {'Dep F1':<8} {'Sui F1':<8} {'Dep→Sui':<10} {'Sui→Dep':<10}")
print("-"*90)
for r in results:
    print(f"{r['model']:<30} {r['accuracy']:<8.4f} {r['weighted_f1']:<8.4f} {r['macro_f1']:<8.4f} "
          f"{r['dep_f1']:<8.4f} {r['sui_f1']:<8.4f} {r['dep_to_sui']:<10} {r['sui_to_dep']:<10}")

with open("classification_comparison_severity.txt", "w", encoding="utf-8") as f:
    f.write("Corrected Classification Model Comparison Table (Normal=0 ... Suicidal=3)\n")
    f.write("="*70 + "\n")
    f.write(f"{'Model':<30} {'Acc':<8} {'W-F1':<8} {'M-F1':<8} {'Dep F1':<8} {'Sui F1':<8} {'Dep→Sui':<10} {'Sui→Dep':<10}\n")
    f.write("-"*90 + "\n")
    for r in results:
        f.write(f"{r['model']:<30} {r['accuracy']:<8.4f} {r['weighted_f1']:<8.4f} {r['macro_f1']:<8.4f} "
                f"{r['dep_f1']:<8.4f} {r['sui_f1']:<8.4f} {r['dep_to_sui']:<10} {r['sui_to_dep']:<10}\n")



Using device: cuda
Severity-ordered label mapping:
  0 -> Normal
  1 -> Anxiety
  2 -> Depression
  3 -> Suicidal

Test set support counts:
  Normal: 2759
  Anxiety: 825
  Depression: 2176
  Suicidal: 1682
数据 + 5个模型定义已就绪

开始训练模型: Baseline


Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: ./hf_models\roberta-base
Key                             | Status     | 
--------------------------------+------------+-
lm_head.dense.bias              | UNEXPECTED | 
lm_head.layer_norm.bias         | UNEXPECTED | 
lm_head.bias                    | UNEXPECTED | 
lm_head.layer_norm.weight       | UNEXPECTED | 
lm_head.dense.weight            | UNEXPECTED | 
roberta.embeddings.position_ids | UNEXPECTED | 
pooler.dense.weight             | MISSING    | 
pooler.dense.bias               | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Epoch 1: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:50<00:00,  5.29it/s]


Epoch 1 Avg Loss: 0.4785 | Val Weighted F1: 0.8351
Best model saved: best_Baseline.pt (Val F1: 0.8351)


Epoch 2: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:49<00:00,  5.30it/s]


Epoch 2 Avg Loss: 0.3219 | Val Weighted F1: 0.8638
Best model saved: best_Baseline.pt (Val F1: 0.8638)


Epoch 3: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:45<00:00,  5.35it/s]


Epoch 3 Avg Loss: 0.2629 | Val Weighted F1: 0.8663
Best model saved: best_Baseline.pt (Val F1: 0.8663)


Epoch 4: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:54<00:00,  5.24it/s]


Epoch 4 Avg Loss: 0.2136 | Val Weighted F1: 0.8578


Epoch 5: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:53<00:00,  5.25it/s]


Epoch 5 Avg Loss: 0.1742 | Val Weighted F1: 0.8620

=== Test Results: Baseline ===
              precision    recall  f1-score   support

      Normal     0.9677    0.9569    0.9623      2759
     Anxiety     0.8534    0.9030    0.8775       825
  Depression     0.8087    0.7831    0.7957      2176
    Suicidal     0.7682    0.7919    0.7799      1682

    accuracy                         0.8628      7442
   macro avg     0.8495    0.8587    0.8538      7442
weighted avg     0.8635    0.8628    0.8629      7442

Confusion Matrix:
[[2640   45   35   39]
 [   8  745   69    3]
 [  42   70 1704  360]
 [  38   13  299 1332]]

开始训练模型: + Class Weight


Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: ./hf_models\roberta-base
Key                             | Status     | 
--------------------------------+------------+-
lm_head.dense.bias              | UNEXPECTED | 
lm_head.layer_norm.bias         | UNEXPECTED | 
lm_head.bias                    | UNEXPECTED | 
lm_head.layer_norm.weight       | UNEXPECTED | 
lm_head.dense.weight            | UNEXPECTED | 
roberta.embeddings.position_ids | UNEXPECTED | 
pooler.dense.weight             | MISSING    | 
pooler.dense.bias               | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Epoch 1: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:51<00:00,  5.27it/s]


Epoch 1 Avg Loss: 0.4786 | Val Weighted F1: 0.8362
Best model saved: best_plus_Class_Weight.pt (Val F1: 0.8362)


Epoch 2: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:50<00:00,  5.29it/s]


Epoch 2 Avg Loss: 0.3435 | Val Weighted F1: 0.8399
Best model saved: best_plus_Class_Weight.pt (Val F1: 0.8399)


Epoch 3: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:48<00:00,  5.31it/s]


Epoch 3 Avg Loss: 0.2807 | Val Weighted F1: 0.8621
Best model saved: best_plus_Class_Weight.pt (Val F1: 0.8621)


Epoch 4: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:49<00:00,  5.31it/s]


Epoch 4 Avg Loss: 0.2388 | Val Weighted F1: 0.8386


Epoch 5: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:48<00:00,  5.31it/s]


Epoch 5 Avg Loss: 0.1946 | Val Weighted F1: 0.8545

=== Test Results: + Class Weight ===
              precision    recall  f1-score   support

      Normal     0.9529    0.9688    0.9608      2759
     Anxiety     0.8315    0.9273    0.8768       825
  Depression     0.8473    0.7192    0.7780      2176
    Suicidal     0.7551    0.8395    0.7950      1682

    accuracy                         0.8620      7442
   macro avg     0.8467    0.8637    0.8527      7442
weighted avg     0.8639    0.8620    0.8606      7442

Confusion Matrix:
[[2673   29   38   19]
 [  22  765   36    2]
 [  55  119 1565  437]
 [  55    7  208 1412]]

开始训练模型: + Multi-label + Severity


Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: ./hf_models\roberta-base
Key                             | Status     | 
--------------------------------+------------+-
lm_head.dense.bias              | UNEXPECTED | 
lm_head.layer_norm.bias         | UNEXPECTED | 
lm_head.bias                    | UNEXPECTED | 
lm_head.layer_norm.weight       | UNEXPECTED | 
lm_head.dense.weight            | UNEXPECTED | 
roberta.embeddings.position_ids | UNEXPECTED | 
pooler.dense.weight             | MISSING    | 
pooler.dense.bias               | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Epoch 1: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:48<00:00,  5.31it/s]


Epoch 1 Avg Loss: 0.2857 | Val Weighted F1: 0.8420
Best model saved: best_plus_Multi-label_plus_Severity.pt (Val F1: 0.8420)


Epoch 2: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:51<00:00,  5.28it/s]


Epoch 2 Avg Loss: 0.2064 | Val Weighted F1: 0.8539
Best model saved: best_plus_Multi-label_plus_Severity.pt (Val F1: 0.8539)


Epoch 3: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:50<00:00,  5.29it/s]


Epoch 3 Avg Loss: 0.1715 | Val Weighted F1: 0.8610
Best model saved: best_plus_Multi-label_plus_Severity.pt (Val F1: 0.8610)


Epoch 4: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:51<00:00,  5.28it/s]


Epoch 4 Avg Loss: 0.1413 | Val Weighted F1: 0.8377


Epoch 5: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:50<00:00,  5.29it/s]


Epoch 5 Avg Loss: 0.1119 | Val Weighted F1: 0.8474

=== Test Results: + Multi-label + Severity ===
              precision    recall  f1-score   support

      Normal     0.9296    0.9761    0.9523      2759
     Anxiety     0.9017    0.8788    0.8901       825
  Depression     0.8462    0.7381    0.7884      2176
    Suicidal     0.7634    0.8365    0.7983      1682

    accuracy                         0.8641      7442
   macro avg     0.8602    0.8574    0.8573      7442
weighted avg     0.8645    0.8641    0.8627      7442

Confusion Matrix:
[[2693   16   35   15]
 [  48  725   50    2]
 [  90   61 1606  419]
 [  66    2  207 1407]]

开始训练模型: + Hierarchical


Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: ./hf_models\roberta-base
Key                             | Status     | 
--------------------------------+------------+-
lm_head.dense.bias              | UNEXPECTED | 
lm_head.layer_norm.bias         | UNEXPECTED | 
lm_head.bias                    | UNEXPECTED | 
lm_head.layer_norm.weight       | UNEXPECTED | 
lm_head.dense.weight            | UNEXPECTED | 
roberta.embeddings.position_ids | UNEXPECTED | 
pooler.dense.weight             | MISSING    | 
pooler.dense.bias               | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Epoch 1: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:53<00:00,  5.25it/s]


Epoch 1 Avg Loss: 0.2735 | Val Weighted F1: 0.8052
Best model saved: best_plus_Hierarchical.pt (Val F1: 0.8052)


Epoch 2: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:51<00:00,  5.27it/s]


Epoch 2 Avg Loss: 0.1577 | Val Weighted F1: 0.8284
Best model saved: best_plus_Hierarchical.pt (Val F1: 0.8284)


Epoch 3: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:48<00:00,  5.32it/s]


Epoch 3 Avg Loss: 0.1139 | Val Weighted F1: 0.8368
Best model saved: best_plus_Hierarchical.pt (Val F1: 0.8368)


Epoch 4: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:52<00:00,  5.27it/s]


Epoch 4 Avg Loss: 0.0841 | Val Weighted F1: 0.8469
Best model saved: best_plus_Hierarchical.pt (Val F1: 0.8469)


Epoch 5: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:51<00:00,  5.28it/s]


Epoch 5 Avg Loss: 0.0646 | Val Weighted F1: 0.8310

=== Test Results: + Hierarchical ===
              precision    recall  f1-score   support

      Normal     0.9682    0.9482    0.9581      2759
     Anxiety     0.8532    0.9018    0.8768       825
  Depression     0.8447    0.6576    0.7395      2176
    Suicidal     0.6854    0.8859    0.7728      1682

    accuracy                         0.8440      7442
   macro avg     0.8379    0.8484    0.8368      7442
weighted avg     0.8554    0.8440    0.8433      7442

Confusion Matrix:
[[2616   50   47   46]
 [  10  744   65    6]
 [  41   72 1431  632]
 [  35    6  151 1490]]

开始训练模型: + Ordinal Regression


Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: ./hf_models\roberta-base
Key                             | Status     | 
--------------------------------+------------+-
lm_head.dense.bias              | UNEXPECTED | 
lm_head.layer_norm.bias         | UNEXPECTED | 
lm_head.bias                    | UNEXPECTED | 
lm_head.layer_norm.weight       | UNEXPECTED | 
lm_head.dense.weight            | UNEXPECTED | 
roberta.embeddings.position_ids | UNEXPECTED | 
pooler.dense.weight             | MISSING    | 
pooler.dense.bias               | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Epoch 1: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:48<00:00,  5.32it/s]


Epoch 1 Avg Loss: 0.2044 | Val Weighted F1: 0.8319
Best model saved: best_plus_Ordinal_Regression.pt (Val F1: 0.8319)


Epoch 2: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:47<00:00,  5.33it/s]


Epoch 2 Avg Loss: 0.1304 | Val Weighted F1: 0.8628
Best model saved: best_plus_Ordinal_Regression.pt (Val F1: 0.8628)


Epoch 3: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:44<00:00,  5.36it/s]


Epoch 3 Avg Loss: 0.1040 | Val Weighted F1: 0.8547


Epoch 4: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:47<00:00,  5.33it/s]


Epoch 4 Avg Loss: 0.0896 | Val Weighted F1: 0.8609


Epoch 5: 100%|███████████████████████████████████████████████████████████████████| 2171/2171 [06:45<00:00,  5.35it/s]


Epoch 5 Avg Loss: 0.0793 | Val Weighted F1: 0.8520

=== Test Results: + Ordinal Regression ===
              precision    recall  f1-score   support

      Normal     0.9511    0.9721    0.9615      2759
     Anxiety     0.8940    0.8279    0.8597       825
  Depression     0.7565    0.8336    0.7932      2176
    Suicidal     0.8116    0.7045    0.7543      1682

    accuracy                         0.8551      7442
   macro avg     0.8533    0.8345    0.8421      7442
weighted avg     0.8563    0.8551    0.8541      7442

Confusion Matrix:
[[2682   30   38    9]
 [  34  683  108    0]
 [  54   42 1814  266]
 [  50    9  438 1185]]

Corrected Classification Model Comparison Table (Severity Order)
Model                          Acc      W-F1     M-F1     Dep F1   Sui F1   Dep→Sui    Sui→Dep   
------------------------------------------------------------------------------------------
Baseline                       0.8628   0.8629   0.8538   0.7957   0.7799   360        299       
+ Clas